plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - spec/**/*
Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Max: 110
Metrics/MethodLength:
  Enabled: false
RSpec/ExampleLength:
  Max: 10
RSpec/MultipleExpectations:
  Enabled: false
